name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]
permissions:
  contents: write
jobs:
  osx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build_osx
  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build_windows